<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateLifeStrengthTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::statement("CREATE TABLE `life_strengths` (
            `id` int(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
            `strength_category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
            `code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
            `achievements_strength` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
            `achievements_strength_hi` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
            `achievements_strength_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
            `image` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
            `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
            `description_hi` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
            `description_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
            `color_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
            `created_at` timestamp NULL DEFAULT NULL,
            `updated_at` timestamp NULL DEFAULT NULL
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC;
        ");
        DB::statement("INSERT INTO `life_strengths` (`id`, `strength_category`, `code`, `achievements_strength`, `achievements_strength_hi`, `achievements_strength_id`, `image`, `description`, `description_hi`, `description_id`, `color_code`, `created_at`, `updated_at`) VALUES
        (1, 'Cognitive', 'CO1', 'Problem Solving', 'समस्या को सुलझाने वाला ', 'Penyelesaian Masalah', '1.01 Problem Solving.png', 'You are always looking for different ways to solve complex problems', 'आप हमेशा जटिल समस्याओं को हल करने के विभिन्न तरीकों की तलाश में रहते हैं', 'Anda selalu mencari cara berbeda untuk menyelesaikan masalah yang rumit', '', NULL, NULL),
        (2, 'Cognitive', 'CO2', 'Decisiveness', 'निश्चितता', 'Ketegasan', '1.02 Decisiveness.png', 'You are comfortable taking the call, even when others are not sure', 'आप निर्णय लेने में सहज होते हैं, भले ही दूसरों को यकीन न हो', 'Anda nyaman dalam mengambil keputusan, bahkan saat yang lain tidak yakin', '', NULL, NULL),
        (3, 'Cognitive', 'CO3', 'Originality', 'अपूर्वता', 'Keorisinilan', '1.03 Originality.png', 'What you think today, others think tomorrow', 'आप लोकप्रिय दृष्टिकोणों से स्वतंत्र रूप से सोचने और नए विचारों को उत्पन्न करने में सक्षम हैं', 'Anda bisa memikirkan sudut pandang populer secara independen dan menghasilkan ide-ide baru', '', NULL, NULL),
        (4, 'Cognitive', 'CO4', 'Simplifying the Complex', 'जटिल को सरल बनाना', 'Menyederhanakan yang Kompleks', '1.04 Simplifying the complex.png', 'You have a way of making complex ideas simple to understand', 'आपके पास जटिल विचारों को आसान बना के समझने का तरीका है', 'Anda memiliki cara menjadikan ide-ide rumit menjadi mudah untuk dimengerti', '', NULL, NULL),
        (5, 'Cognitive', 'CO5', 'Connecting the Dots', 'बिंदुओं को जोड़ें', 'Menghubungkan Titik - Titik', '1.04 Connecting the dots.png', 'You bring ideas from different worlds together, to form new possibility', 'आप विभिन्न दुनिया के विचारों को एक साथ लाते हैं, जिससे नई संभावना बनती है', 'Anda membawa ide dari dunia lain bersama, untuk membentuk kemungkinan baru', '', NULL, NULL),
        (6, 'Cognitive', 'CO6', 'Thinking ahead', 'आगे की सोचना', 'Berpikir Ke depan', '1.06 Thinking Ahead.png', 'You are able to see around corners, and predict what happens next.', 'आप चारों ओर देख सकते हैं, और भविष्यवाणी कर सकते हैं कि आगे क्या हो सकता है', 'Anda bisa melihat di sekitar, dan memprediksi apa yang terjadi berikutnya', '', NULL, NULL),
        (7, 'Cognitive', 'CO7', 'Sense Making', 'अर्थपुर्ण', 'Pemahaman Makna', '1.07 Sense Making.png', 'The world is chaotic, but you can make sense of it for others', 'यह दुनिया अराजक है, लेकिन आप इसे दूसरों के लिए व्याख्या कर सकते हैं', 'Dunia ini kacau, tetapi Anda bisa mengartikannya untuk orang lain', '', NULL, NULL),
        (8, 'Interactive', 'IN1', 'Collaborating', 'साथ मिलाकर काम करना', 'Berkolaborasi', '2.01 Collaborating.png', 'You are easy to work with, and you, in turn love to collaborate with others from different fields', 'आप के साथ काम करना आसान है, और आप विभिन्न क्षेत्रों के अन्य लोगों के साथ काम करने में आनंद लेते हैं', 'Anda mudah untuk diajak bekerja, dan Anda, sebagai gantinya senang bekerja sama dengan orang lain dari bidang yang berbeda', '', NULL, NULL),
        (9, 'Interactive', 'IN2', 'Valuing Relationships', 'रिश्तों को महत्व देना', 'Menghargai Hubungan', '2.03 Valuing relationships.png', 'You value deep and lasting relationships nurtured on mutual trust and respect', 'आप गहरे और दीर्घकालिक रिश्तों को महत्व देते हैं जिनका पालन-पोषण विश्वास और सम्मान के साथ होता है', 'Anda menghargai hubungan yang dalam dan berjangka panjang yang dipupuk dengan kepercayaan dan respek', '', NULL, NULL),
        (10, 'Interactive', 'IN3', 'Engagement', 'भाग लेना', 'Keterikatan', '2.04 Engagement.png', 'People tend to be drawn to you, they find it engaging to interact with you', 'लोग आपकी ओर आकर्षित होते हैं, उन्हें आपसे बातचीत करना दिलचस्प लगता है', 'Orang-orang cenderung tertarik pada Anda, mereka menganggapnya menarik untuk berinteraksi dengan Anda', '', NULL, NULL),
        (11, 'Interactive', 'IN4', 'Diplomacy', 'व्यवहार-कुशलता', 'Diplomasi', '2.02 Diplomacy.png', 'When conflict arises, you are often the one to resolve tensions', 'जब टकराव पैदा होता है, तो आप अक्सर समस्या का समाधान करने वाले व्यक्ति बन जाते हैं', 'Saat konflik muncul, Anda sering kali menjadi orang yang menyelesaikan masalah', '', NULL, NULL),
        (12, 'Interactive', 'IN5', 'Eloquence', 'उत्तम बोली', 'Kefasihan', '2.05 Eloquence.png', 'You can communicate with different audiences in compelling ways', 'आप दिलचस्प तरीकों से विभिन्न दर्शकों के साथ संवाद कर सकते हैं', 'Anda bisa berkomunikasi dengan audiensi berbeda dengan cara yang menarik', '', NULL, NULL),
        (13, 'Interactive', 'IN6', 'Social Flexibility', 'सामाजिक लचीलापन', 'Fleksibilitas Sosial', '2.06 Socil Flexibility.png', 'You enjoy building connections with people across cultures and social groups', 'आप विभिन्न सांस्कृतिक और सामाजिक समूहों के लोगों के साथ संबंध बनाना पसंद करते हैं', 'Anda senang membangun koneksi dengan orang-orang berbagai kelompok budaya dan sosial', '', NULL, NULL),
        (14, 'Interactive', 'IN7', 'Being Persuasive', 'अनुशीलनशील होना', 'Persuasif', '2.07 Being Persuasive.png', 'You can persuade others and sway opinion, even when you don’t have any power over them', 'आप दूसरों को मना सकते हैं और राय को हिला सकते हैं, तब भी जब आप उन पर कोई अधिकार नहीं रखते', 'Anda bisa membujuk orang lain dan menggoyahkan pendapat, bahkan saat Anda tidak memiliki kekuatan diatas mereka', '', NULL, NULL),
        (15, 'Emotive', 'EM1', 'Empathy', 'हमदर्दी', 'Empati', '3.01 Empathy.png', 'You can put yourself in others\' shoes, even those who don’t like you', 'आप खुद को किसी और  व्यक्ति की जगह रख कर दूसरों की समस्या, स्थिति,राय या दृष्टिकोण समझ सकते हैं, यहां तक कि उन लोगों को भी जो आपको पसंद नहीं करते हैं', 'Anda bisa menempatkan diri Anda di pribadi orang lain, bahkan mereka yang tidak menyukai Anda', '', NULL, NULL),
        (16, 'Emotive', 'EM2', 'Self Awareness', 'आत्म जागरूकता', 'Kesadaran Diri', '3.03 Self Awareness.png', 'You are comfortable with who you are and don’t profess to be who you are not', 'आप इस बात से सहज हैं कि आप कौन हैं और आप जो नहीं हैं, उसके होने का दावा नहीं करते हैं', 'Anda nyaman dengan siapa diri Anda dan tidak berpura-pura untuk menjadi orang lain', '', NULL, NULL),
        (17, 'Emotive', 'EM3', 'Calmness', 'शांति', 'Ketenangan', '3.04 Calmness.png', 'When things go crazy, people turn to you for level headed wisdom', 'जब चीजें बिगड़ जाती हैं, तो लोग आपके पास ज्ञान के लिए जाते हैं', 'Saat hal-hal menggila, orang-orang pergi pada Anda untuk kebijaksanaan', '', NULL, NULL),
        (18, 'Emotive', 'EM4', 'Trust', 'भरोसा', 'Kepercayaan', '3.05 Trust.png', 'You can trust people unconditionally, even if they let you down from time to time', 'आप बिना किसी अपवाद के लोगों पर भरोसा कर सकते हैं, भले ही वे आपको समय-समय पर निराश करते हों', 'Anda bisa mempercayai orang dengan tanpa pengecualian, bahkan jika mereka mengecewakan Anda dari waktu ke waktu', '', NULL, NULL),
        (19, 'Emotive', 'EM5', 'Patience', 'धीरज', 'Kesabaran', '3.06 Patience.png', 'When things go wrong you don\'t lose your spirit ... when things go well you don\'t lose your head', 'जब आप चीज़ें आप को मुताबिक नहीं होती तो आप हिम्मत नहीं हारते ...जब सब कुछ आसानी से हो जाता है तो आप घमण्ड नहीं करते हैं', 'Saat ada yang salah Anda tidak kehilangan semangat … saat semua berjalan lancar Anda tidak besar kepala', '', NULL, NULL),
        (20, 'Emotive', 'EM6', 'Gratitude', 'प्रति आभार', 'Bersyukur', '3.07 Gratitude.png', 'You feel a deep sense of thankfulness for what you have, rather than bitterness at what you don’t', 'आपके पास जो कुछ भी है उसके लिए आप बहुत आभारी हैं, और आपके पास जो कुछ भी नहीं है, उसका विलाप नहीं करते हैं', 'Anda merasa amat bersyukur dengan apa yang Anda miliki, dan tidak meratapi apa yang tidak Anda miliki', '', NULL, NULL),
        (21, 'Emotive', 'EM7', 'Compassion', 'दया', 'Rasa Pengertian', '3.02 Compassion.png', 'You are able to feel for and stand for those who may not be deserving of kindness', 'आप उन लोगों को महसूस कर सकते हैं और उनका बचाव कर सकते हैं जो अच्छाई के हकदार नहीं हो सकते', 'Anda bisa merasakan dan membela mereka yang mungkin tidak berhak akan kebaikan', '', NULL, NULL),
        (22, 'Adaptive', 'AD1', 'Resilience', 'लचीलाता', 'Ketahanan', '5.02 Resilience.png', 'When faced with disappointement and failure you can bounce back with ease', 'जब आप को निराशा और असफलता हाथ लगती है तो आप उसे हमेशा आसानी से सामना करते हैं', 'Saat dihadapkan dengan kekecewaan dan kegagalan Anda selalu bangkit kembali dengan mudah', '', NULL, NULL),
        (23, 'Adaptive', 'AD2', 'Dealing with Adversity', 'कठिनाई से निपटना', 'Mampu dalam Menghadapi Kesulitan', '5.03 Dealing with Adversity.png', 'Adverse situations don’t discourage you, they give you energy to act', 'बुरी स्थितियाँ आपको हतोत्साहित नहीं करती हैं, इससे आपको कार्य करने की शक्ति मिलती है', 'Situasi yang buruk tidak mengecilkan hati Anda, ini memberikan Anda kekuatan untuk bertindak', '', NULL, NULL),
        (24, 'Adaptive', 'AD3', 'Will Power', 'इच्छा शक्ति', 'Kemauan Tinggi', '5.04 Will Power.png', 'When you decide to do something, nothing can stop you … even your own doubts', 'जब आप कुछ करने का फैसला करते हैं, तो कुछ भी आपको रोक नहीं सकता है ... यहां तक कि आपके खुद के संदेह भी', 'Saat Anda memutuskan untuk melakukan sesuatu, tidak ada yang bisa menghentikan Anda … bahkan keraguan Anda sendiri', '', NULL, NULL),
        (25, 'Adaptive', 'AD4', 'Self Discipline', 'आत्मानुशासन', 'Kedisiplinan Diri', '5.05 Self Discipline.png', 'You can control your emotions and urges and stay true to your mission at all times', 'आप अपनी भावनाओं और इच्छाओं को नियंत्रित कर सकते हैं और किसी भी समय अपने मिशन पर खरे रह सकते हैं', 'Anda bisa mengendalikan emosi dan keinginan Anda dan tetap setia pada misi Anda pada kapanpun', '', NULL, NULL),
        (26, 'Adaptive', 'AD5', 'Persistence', 'दृढ़ता', 'Ketekunan', '5.01 Persistence.png', 'You will try, try, and try again … until the world gets out of your way', 'आप तब तक कोशिश करेंगे, कोशिश करेंगे, और फिर कोशिश करेंगे… जब तक कि दुनिया आपके रास्ते से हट नहीं जाती', 'Anda akan mencoba, mencoba, dan mencoba lagi … hingga dunia tidak menghalangi Anda lagi', '', NULL, NULL),
        (27, 'Adaptive', 'AD6', 'Humility', 'विनम्रता', 'Kerendahan Hati', '5.06 Humility.png', 'You have control over your ego and can question your beliefs when confronted with reality', 'आप अपने अहंकार पर नियंत्रण रखते हैं और वास्तविकता से सामना होने पर अपनी मान्यताओं पर सवाल उठा सकते हैं', 'Anda memiliki kendali atas ego Anda dan bisa mempertanyakan kepercayaan Anda saat dihadapkan dengan realita', '', NULL, NULL),
        (28, 'Adaptive', 'AD7', 'Agility', 'चुस्ती', 'Kesigapan', '5.07 Agility.png', 'You have the agility to adapt to any situation (good or bad) and make the most of the cards you hold', 'आपके पास किसी भी स्थिति (अच्छा या बुरा) के अनुकूल होने और आपके पास जो कुछ भी है उसे अधिकतम करने की क्षमता है', 'Anda memiliki kelincahan untuk beradaptasi dengan situasi apapun (baik atau buruk) dan memaksimalkan apa yang Anda miliki', '', NULL, NULL),
        (29, 'Creative', 'CR1', 'Curiosity', 'जिज्ञासा', 'Keingintahuan', '4.01 Curiosity.png', 'You have an urge to find out, about things and people who may not have any obvious value to you', 'आप उन लोगों के बारे में और उन चीज़ों  के बारे जानना की इच्छा रखते हैं जो उतने महत्वपूर्ण  नहीं होते', 'Anda memiliki keinginan untuk mencari tahu, tentang hal-hal dan orang-orang yang mungkin tidak memiliki nilai yang penting bagi Anda', '', NULL, NULL),
        (30, 'Creative', 'CR2', 'Critical Thinking', 'गहन सोच', 'Berpikiran Kritis', '4.02 Critical Thinking.png', 'You are always questioning why things are the way they are, taking nothing for granted', 'आप हमेशा पूछते हैं कि चीज़ें ऐसा क्यों है और किसी भी चीज़ को स्थाई नहीं समझते', 'Anda selalu mempertanyakan mengapa begini dan begitu, tidak menyia-nyiakan apapun', '', NULL, NULL),
        (31, 'Creative', 'CR3', 'Taking Risk', 'जोखिम लेना', 'Mengambil Risiko', '4.03 Taking Risk.png', 'Doing things that you believe need doing but have a small chance of success come naturally to you', 'जो आप मानते हैं उसे करने के लिए आवश्यक प्रयास होती है, भले ही थोड़ी सफलता मिले पर सफ़लता स्वाभिक तौर पर मिलती है', 'Melakukan apa yang Anda percayai memerlukan usaha tetapi peluang kecil keberhasilannya datang secara alami kepada Anda', '', NULL, NULL),
        (32, 'Creative', 'CR4', 'Entrepreneurship', 'उद्यमिता', 'Kewirausahaan', '4.04 Entrepreneurship.png', 'You enjoy building things from scratch, and creating value from nothing', 'आप स्क्रैच से चीजों का निर्माण करना पसंद करते हैं,और वो चीज़ें जिसका कोई मूल्य नहीं होता उसको आप मूलयवान बना देते हैं', 'Anda senang membangun dari awal, dan menghargai nilai dari nol', '', NULL, NULL),
        (33, 'Creative', 'CR5', 'Exploring', 'खोज', 'Bereksplorasi', '4.05 Exploring.png', 'When others ask \'why\', you are asking \'why not\'', 'जब अन्य लोग \'क्यों\' पूछते हैं, तो आप \'क्यों नहीं\' पूछ रहे हैं', 'Saat yang lain bertanya \'mengapa\', Anda bertanya \'mengapa tidak\'', '', NULL, NULL),
        (34, 'Creative', 'CR6', 'Pioneering', 'अनुसंधान', 'Mempelopori', '4.06 Pioneering.png', 'You enjoy being the first to do something even if it means a high chance of failure', 'आपको सबसे पहले कुछ करने में आनंद मिलता है, भले ही विफलता की उच्च संभावना हो', 'Anda senang menjadi yang pertama untuk melakukan sesuatu bahkan jika peluang gagalnya tinggi', '', NULL, NULL),
        (35, 'Creative', 'CR7', 'Challenging the Norm', 'सामान्य चुनौती', 'Berani Menjadi Beda', '4.07 Challenging the norm.png', 'You challenge the way things are, even when things are going well', 'आप चीजों को चुनौती देते हैं कि जब चीजें ठीक चल रही हों, तब भी', 'Anda menantang hal-hal, bahkan jika semuanya baik-baik saja', '', NULL, NULL),
        (36, 'Motive', 'MO1', 'Drive', 'अभियान', 'Dorongan', '6.01 Drive.png', 'You bring positive energy to life … energy that comes from inside you … and touches others', 'आप जीवन में सकारात्मक ऊर्जा लाते हैं… आपके अंदर से जो ऊर्जा आती है… और दूसरों को छूती हैं', 'Anda membawa energi positif dalam hidup … energi yang datang dari dalam Anda … dan menyentuh orang lain', '', NULL, NULL),
        (37, 'Motive', 'MO2', 'Passion', 'जुनून', 'Keinginan', '6.03 Passion.png', 'You are driven by your cause …  and infect others to feel passionately for your cause', 'आप अपने कारण से प्रेरित होते हैं ... और दूसरों को अपने कारण के लिए लगन से प्रभावित करते हैं', 'Anda didorong oleh sebab … dan mempengaruhi orang lain untuk merasakan yang sama untuk sebab tersebut', '', NULL, NULL),
        (38, 'Motive', 'MO3', 'Confidence', 'आत्मविश्वास', 'Kepercayaan Diri', '6.04 Confidence.png', 'You believe in yourself, and will back yourself even when others may not', 'आप खुद पर विश्वास करते हैं, और दूसरों के न होने पर भी खुद पर विश्वाश करते हैं ', 'Anda mempercayai diri Anda, dan akan menopang diri Anda sendiri saat orang lain tidak', '', NULL, NULL),
        (39, 'Motive', 'MO4', 'Integrity', 'ईमानदारी', 'Integritas', '6.05 Integrity.png', 'You do what you say, and say what you do', 'आप वही करते हैं जो आप कहते हैं, और वही कहते हैं जो आप करते हैं', 'Anda melakukan yang Anda katakan, dan mengatakan yang Anda lakukan', '', NULL, NULL),
        (40, 'Motive', 'MO5', 'Dependability', 'निर्भरता', 'Dapat Diandalkan', '6.02 Dependability.png', 'When you take responsibility for something you can be counted on to get it done', 'जब आप किसी चीज़ की ज़िम्मेदारी लेते हैं तो आप उसे पूरा करते हैं', 'Saat Anda mengambil tanggung jawab untuk sesuatu Anda bisa diandalkan untuk menyelesaikannya', '', NULL, NULL),
        (41, 'Motive', 'MO6', 'Objectivity', 'निष्पक्षतावाद', 'Objektivitas', '6.06 Objectivity.png', 'You see reality through the lens of evidence and facts, not through beliefs and opinions', 'आप वास्तविकता को प्रमाणों और तथ्यों के लेंस के माध्यम से देखते हैं, विश्वासों और विचारों के माध्यम से नहीं', 'Anda melihat realita melalui lensa bukti dan fakta, bukan melalui kepercayaan dan opini', '', NULL, NULL),
        (42, 'Motive', 'MO7', 'Sense of Purpose', 'उद्देश्य की भावना', 'Rasa Memiliki Tujuan', '6.07 Sense of Purpose.png', 'Your personal mission motivates you, not money or titles or others\' expectations of you', 'आपका व्यक्तिगत मिशन आपको प्रेरित करता है, न कि पैसा या शीर्षक या दूसरों की अपेक्षाएँ', 'Misi pribadi Anda memotivasi Anda, bukan uang atau gelar atau harapan orang lain terhadap Anda', '', NULL, NULL);"
        );
        DB::statement("ALTER TABLE `life_strengths`
        MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=43;");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('life_strength');
    }
}
